### ISSUE TITLE
Fatal Exeption on low end device

### ISSUE THREAD

**Issue by JackJagt** [0x48lab/flutter_body_detection#2]
**Thank you for your help and answers. 
On lowend device I stil get the exeption** 
I/CameraManagerGlobal(10088): Connecting to camera service
D/CameraRepository(10088): Added camera: 0
I/Camera2CameraInfo(10088): Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_LEGACY
D/UseCaseAttachState(10088): Active and attached use case: [] for camera: 0
D/AndroidRuntime(10088): Shutting down VM
E/AndroidRuntime(10088): FATAL EXCEPTION: main
E/AndroidRuntime(10088): Process: com.u0x48lab.body_detection_example, PID: 10088
E/AndroidRuntime(10088): java.lang.IllegalArgumentException: No available camera can be found.
E/AndroidRuntime(10088): 	at androidx.camera.core.CameraSelector.filter(CameraSelector.java:107)
E/AndroidRuntime(10088): 	at androidx.camera.core.CameraSelector.filter(CameraSelector.java:137)
E/AndroidRuntime(10088): 	at androidx.camera.lifecycle.ProcessCameraProvider.bindToLifecycle(ProcessCameraProvider.java:388)
E/AndroidRuntime(10088): 	at androidx.camera.lifecycle.ProcessCameraProvider.bindToLifecycle(ProcessCameraProvider.java:274)
E/AndroidRuntime(10088): 	at com.u0x48lab.body_detection.CameraSession.bindAnalysisUseCase(CameraSession.kt:120)
E/AndroidRuntime(10088): 	at com.u0x48lab.body_detection.CameraSession.access$bindAnalysisUseCase(CameraSession.kt:17)
E/AndroidRuntime(10088): 	at com.u0x48lab.body_detection.CameraSession$1.run(CameraSession.kt:32)
E/AndroidRuntime(10088): 	at android.os.Handler.handleCallback(Handler.java:790)
E/AndroidRuntime(10088): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(10088): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(10088): 	at android.app.ActivityThread.main(ActivityThread.java:6523)
E/AndroidRuntime(10088): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10088): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/AndroidRuntime(10088): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)

**Comment by JackJagt** [comment]
I got it finally working, I had to change Front to Back (it's only upside down)
I had to do this only for this device because the API sees the camera as back, although it's front 
Thank you for your help
class CameraSession(private var context: Context) {
    private var processOutput: ((ImageProxy, Int) -> Unit)? = null
    private var cameraProvider: ProcessCameraProvider? = null
    private var analysisUseCase: ImageAnalysis? = null
    private var lensFacing = CameraSelector.LENS_FACING**_BACK**
    private var cameraSelector = CameraSelector.DEFAULT_**BACK**_CAMERA
    private val lifecycle = CustomLifecycle()
![Pose detection](https://user-images.githubusercontent.com/36696633/152206812-0d61bf2f-8905-4d24-90c9-c464661fc7f1.jpg)

**Comment by dcwhitt** [comment]
Hey JackJagt, 
   I'm also trying to switch to the back camera. Where did you put in that code to change from front to back camera? Thanks!

**Comment by JackJagt** [comment]
Hello dcwhitt
I changed front to back in the following code, but that is because one of my devices has no back camera and the software detect is as back camera.

class CameraSession(private var context: Context) {
    private var processOutput: ((ImageProxy, Int) -> Unit)? = null
    private var cameraProvider: ProcessCameraProvider? = null
    private var analysisUseCase: ImageAnalysis? = null
    private var lensFacing = CameraSelector.LENS_FACING_**BACK**
    private var cameraSelector = CameraSelector.DEFAULT_**BACK**_CAMERA
    private val lifecycle = CustomLifecycle()

**Comment by dcwhitt** [comment]
Thanks! Did you put that code in your main.dart file? I appreciate your help.

**Comment by JackJagt** [comment]
I changed it in Camerasesion.kt but be aware that it is typical for this hardware without back camera

**Comment by dcwhitt** [comment]
Great thanks. With how the plug-in works, if i was to use the flutter camera plugin instead and load in a default camera ahead of time (like when I run the app) think it would use that camera? I'll try it this afternoon hopefully!

**Comment by Enzotic** [comment]
Hi,  I'm still an amateur on flutter programming. May I ask, how were you able to change the variables? Did you download CameraSession.kt? I'm trying to change the camera resolution.

**Comment by JackJagt** [comment]
Hello Enczotic 
I'm not a flutter developer either but i canged it in visual studio code.
